feat: add configuration and shell module improvements for SnowBlower

diff --git a/snow b/snow
--- a/snow
+++ b/snow
@@ -4,8 +4,6 @@
 #  SnowBlower: All Flake No Fluff
 #  https://github.com/use-the-fork/snowblower
 #
-#
-###############################################################################################
 
 set -e
 set -o pipefail
@@ -73,7 +71,7 @@ function executeWithSpinner() {
   # Show spinner while command runs
   local i=0
   while kill -0 $cmd_pid 2>/dev/null; do
-    printf "\r${WHITE}[ ${YELLOW}%s${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}" \
+    printf "\r${WHITE}[ ${BLUE}%s${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}" \
       "${spinner:i:1}" "$message" "$detail"
     i=$(((i + 1) % ${#spinner}))
     sleep 0.1
@@ -85,10 +83,9 @@ function executeWithSpinner() {
 
   # Show final status
   if [ $exit_code -eq 0 ]; then
-    printf "\r${WHITE}[ ${GREEN} OK ${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "$message" "$detail"
+    echoOk "$message" "$detail"
   else
-    printf "\r${WHITE}[ ${RED}FAIL${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "$message" "$detail"
-    # Optionally show the output on failure
+    echoFail "$message" "$detail"
     cat "$temp_file"
   fi
 
@@ -98,45 +95,58 @@ function executeWithSpinner() {
 
 function echoSnow() {
   local message="${1:-}"
-  echo "${WHITE}[ ${GREEN} ❄️💨 ${WHITE} ]  ${BOLD}${WHITE}${message}${NC}"
+  printf "${WHITE}[ ${GREEN} ❄️💨 ${WHITE} ]  ${BOLD}${WHITE}%s${NC}\n" "${message}"
 }
 function echoOk() {
   local message="${1:-}"
   local detail="${2:-}"
-  echo "${WHITE}[ ${GREEN} OK ${WHITE} ]  ${NC}${DIM}${message}${NC} ${WHITE}${detail}${NC}"
+  printf "${WHITE}[ ${GREEN} OK ${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "${message}" "${detail}"
 }
 function echoWarn() {
   local message="${1:-}"
   local detail="${2:-}"
-  echo "${WHITE}[ ${YELLOW}WARN${WHITE} ]  ${NC}${DIM}${message}${NC} ${WHITE}${detail}${NC}"
+  printf "${WHITE}[ ${YELLOW}WARN${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "${message}" "${detail}"
 }
 function echoFail() {
   local message="${1:-}"
   local detail="${2:-}"
-  echo "${WHITE}[ ${RED}FAIL${WHITE} ]  ${NC}${DIM}${message}${NC} ${WHITE}${detail}${NC}"
+  printf "${WHITE}[ ${RED}FAIL${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "${message}" "${detail}"
 }
 function statusInfo() {
   local message="${1:-}"
   local detail="${2:-}"
-  echo "${WHITE}[ ${BLUE}INFO${WHITE} ]  ${NC}${DIM}${message}${NC} ${WHITE}${detail}${NC}"
+  printf "${WHITE}[ ${BLUE}INFO${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "${message}" "${detail}"
 }
 function echoBlank() {
   local message="${1:-}"
   local detail="${2:-}"
-  echo "          ${NC}${DIM}${message}${NC} ${WHITE}${detail}${NC}"
+  printf "          ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "${message}" "${detail}"
 }
 function echoDebug() {
   local message="${1:-}"
   local detail="${2:-}"
 
   if [ -n "${DEBUG:-}" ]; then
-    echo "${WHITE}[ ${YELLOW}DEBUG${WHITE} ]  ${NC}${DIM}${message}${NC} ${WHITE}${detail}${NC}"
+    printf "${WHITE}[ ${YELLOW}DEBUG${WHITE} ]  ${NC}${DIM}%s${NC} ${WHITE}%s${NC}\n" "${message}" "${detail}"
   fi
 }
-function echoVerbose() {
-  if [[ -v VERBOSE ]]; then
-    echo "$*"
-  fi
+
+# Credits: https://github.com/srid/flake-root/blob/master/flake-module.nix
+# This function is used to find the flake root and set it as a env varible.
+__sb__findUp() {
+  ancestors=()
+  while true; do
+    if [[ -f $1 ]]; then
+      echo "$PWD"
+      exit 0
+    fi
+    ancestors+=("$PWD")
+    if [[ $PWD == / ]] || [[ $PWD == // ]]; then
+      echo "Unable to locate ${1}"
+      exit 1
+    fi
+    cd ..
+  done
 }
 
 function __sb__createTouchFile() {
@@ -186,7 +196,7 @@ function __sb__hasNix() {
 }
 
 function __sb__isInsideSnowblowerShell() {
-  if [ -n "$SB_IS_SHELL" ]; then
+  if [ -n "$SB_IN_SHELL" ]; then
     return 0
   else
     return 1
@@ -231,16 +241,29 @@ elif [ -f ./.env ]; then
   source ./.env
   echoOk "Found and sourced" ".env"
 fi
-$()
+
 # Create a session file in tmp dir. this allows us to do the "heavy" lifiting for the snow command one time.
 SCRIPT_HASH=$(echo "${BASH_SOURCE[0]}" | md5sum | cut -d' ' -f1 | cut -c1-8)
 export SB_SESS_FILE="${TMPDIR:-/tmp}/.sb_session_$(tty | tr '/' '_')_${SCRIPT_HASH}"
 
 # we define environment variables...
+# export SB_SRC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+echoDebug "${BASH_SOURCE[0]}"
+
 export SB_APP_SERVICE=${APP_SERVICE:-"snowblower-dev"}
 export SB_USER_UID=${USER_UID:-$UID}
 export SB_USER_GID=${USER_GID:-$(id -g)}
 export SB_SKIP_CHECKS=${SKIP_CHECKS:-}
+export SB_PROJECT_ROOT_FILE=${PROJECT_ROOT_FILE:-"flake.nix"}
+
+SB_SRC_ROOT="$(__sb__findUp "$SB_PROJECT_ROOT_FILE")"
+if [ $? -ne 0 ]; then
+  echoFail "Unable to locate $SB_PROJECT_ROOT_FILE" "Make sure you're in a project directory with a $SB_PROJECT_ROOT_FILE file"
+  exit 1
+fi
+
+export SB_SRC_ROOT
 
 function __sb__bootSnowBlowerEnvironment() {
   # Only source this once.
@@ -255,14 +278,12 @@ function __sb__bootSnowBlowerEnvironment() {
   echoOk "Creating Session File" "${SB_SESS_FILE}"
 
   # These are the must have varibles for the project
-  export SB_SRC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
   export SB_PROJECT_ROOT="$SB_SRC_ROOT/.snowblower"
   export SB_PROJECT_PROFILE="$SB_PROJECT_ROOT/profile"
   export SB_PROJECT_STATE="$SB_PROJECT_ROOT/state"
   export SB_PROJECT_RUNTIME="$SB_PROJECT_ROOT/runtime"
 
   # Save exports to session file
-  echo "export SB_SRC_ROOT=\"$SB_SRC_ROOT\"" >"$SB_SESS_FILE"
   echo "export SB_PROJECT_ROOT=\"$SB_PROJECT_ROOT\"" >>"$SB_SESS_FILE"
   echo "export SB_PROJECT_PROFILE=\"$SB_PROJECT_PROFILE\"" >>"$SB_SESS_FILE"
   echo "export SB_PROJECT_STATE=\"$SB_PROJECT_STATE\"" >>"$SB_SESS_FILE"
@@ -302,7 +323,7 @@ function __sb__bootSnowBlowerEnvironment() {
     fi
   fi
 
-  echoOk "SnowBlower directory set to" "${SB_PROJECT_ROOT}"
+  echoOk "SnowBlower root directory set to" "${SB_SRC_ROOT}"
 
   # Create directories if they don't exist
   if [ ! -d "$SB_PROJECT_ROOT" ]; then
@@ -323,6 +344,9 @@ function __sb__bootSnowBlowerEnvironment() {
     echoOk "Creating runtime directory" "${SB_PROJECT_RUNTIME}"
     mkdir -p "$SB_PROJECT_RUNTIME"
   fi
+
+  #Symlink SnowBlower to the profile
+  ln -sf "${SB_SRC_ROOT}/snow" "${SB_PROJECT_PROFILE}/snow"
 
   # the below two function are added via a seperate package in files.nix.
   # But we need to boot it here so we can be sure all directories are created.
@@ -464,13 +488,13 @@ function __sb__command__docker__build {
 # Commands that are specific to controling SnowBlower.
 function __sb__command__switch {
   nix run .#snowblowerFiles
-  return $?
+  return 0
 }
 function __sb__command__update {
   executeWithSpinner "Updating Flake" "nix flake update"
   __sb__command__switch
   __sb__command__reboot
-  return $?
+  return 0
 }
 
 function __sb__command__reboot() {
