refactor: simplify snow command parsing and error handling

diff --git a/snow b/snow
--- a/snow
+++ b/snow
@@ -113,6 +113,12 @@ function checkLastCommand() {
 	fi
 }
 
+# Run a command that should never fail. If the command fails execution
+# will immediately terminate with an error showing the failing
+# command.
+ensure() {
+	if ! "$@"; then _iFail "command failed: $*"; fi
+}
 # Credits to https://github.com/nix-community/home-manager/blob/master/lib/bash/home-manager.sh
 # The setup respects the `NO_COLOR` environment variable.
 
@@ -334,7 +340,8 @@ function _iError() {
 }
 
 function _iFail() {
-	_iError "$@"
+	_iError "$@" >&2
+	exit 1
 }
 
 function _iWarn() {
@@ -496,34 +503,29 @@ function doSnowBuildImagesLogic() {
 
 	_iSnow "Rebuilding Images"
 
-	cursorSave
 	_iNote "Pruning Old Images"
-	runDocker image prune -f --filter "label=org.snowblower.project=$SB_PROJECT_HASH"
-	checkLastCommand "Pruned Old Images" "Prune Failed" 1
+	ensure runDocker image prune -f --filter "label=org.snowblower.project=$SB_PROJECT_HASH"
+	_iOk "Pruned Images"
 
 	rm -f "$SB_PROJECT_ROOT/result"
 
-	cursorSave
 	_iNote "Building Runtime Docker Image"
-	runBuilder nix build --impure --out-link "/snowblower/result" .#dockerRuntimeImagePackage
-	checkLastCommand "Building Runtime Docker Image" "Build Failed" 1
+	ensure runBuilder nix build --impure --out-link "/snowblower/result" .#dockerRuntimeImagePackage
+	_iOk "Built Runtime Docker Image"
 
-	cursorSave
 	_iNote "Loading Runtime Docker Image"
-	runBuilder bash -c "/snowblower/result | sudo docker load"
-	checkLastCommand "Loading Runtime Docker Image" "Load Failed" 1
+	ensure runBuilder bash -c "/snowblower/result | sudo docker load"
+	_iOk "Loaded Runtime Docker Image"
 
 	rm -f "$SB_PROJECT_ROOT/result"
 
-	cursorSave
 	_iNote "Building Tooling Docker Image"
-	runBuilder nix build --impure --out-link "/snowblower/result" .#dockerToolsImagePackage
-	checkLastCommand "Building Tooling Docker Image" "Build Failed" 1
+	ensure runBuilder nix build --impure --out-link "/snowblower/result" .#dockerToolsImagePackage
+	_iOk "Built Tooling Docker Image"
 
-	cursorSave
 	_iNote "Loading Tooling Docker Image"
-	runBuilder bash -c "/snowblower/result | sudo docker load"
-	checkLastCommand "Loading Tooling Docker Image" "Load Failed" 1
+	ensure runBuilder bash -c "/snowblower/result | sudo docker load"
+	_iOk "Loaded Tooling Docker Image"
 
 	rm -f "$SB_PROJECT_ROOT/result"
 
@@ -834,128 +836,137 @@ function doHelp {
 	exit 1
 }
 
-PASSTHROUGH_OPTS=()
+doSnow() {
+	PASSTHROUGH_OPTS=()
 
-SNOW_COMMAND=""
-SNOW_COMMAND_ARGS=()
+	SNOW_COMMAND=""
+	SNOW_COMMAND_ARGS=()
 
-COMMAND=""
-SUBCOMMAND=""
-COMMAND_ARGS=()
+	COMMAND_ARGS=()
 
-# Split arguments at the `--` separator
-BEFORE_SEPARATOR=()
-AFTER_SEPARATOR=()
+	# Split arguments at the `--` separator
+	BEFORE_SEPARATOR=()
+	AFTER_SEPARATOR=()
 
-# Used here to split the function in to anything before '--' and after.
-FOUND_SEPARATOR=false
-for arg in "$@"; do
-	if [[ $arg == "--" ]]; then
-		FOUND_SEPARATOR=true
-		continue
-	fi
+	# Used here to split the function in to anything before '--' and after.
+	FOUND_SEPARATOR=false
+	for arg in "$@"; do
+		if [[ $arg == "--" ]]; then
+			FOUND_SEPARATOR=true
+			continue
+		fi
 
-	if [[ $FOUND_SEPARATOR == true ]]; then
-		AFTER_SEPARATOR+=("$arg")
-	else
-		BEFORE_SEPARATOR+=("$arg")
-	fi
-done
+		if [[ $arg == "---" ]]; then
+			FOUND_SEPARATOR=true
+			AFTER_SEPARATOR+=("just")
+			continue
+		fi
 
-# Process snow-specific options and commands before `--`
-i=0
-while [[ $i -lt ${#BEFORE_SEPARATOR[@]} ]]; do
-	opt="${BEFORE_SEPARATOR[$i]}"
-	i=$((i + 1))
+		if [[ $FOUND_SEPARATOR == true ]]; then
+			AFTER_SEPARATOR+=("$arg")
+		else
+			BEFORE_SEPARATOR+=("$arg")
+		fi
+	done
 
-	case $opt in
-	-v | --verbose)
-		export VERBOSE=1
-		;;
-	-h | --help)
-		export HELP=1
-		;;
-	-b | --build)
-		export BUILD=1
-		;;
-	--version)
-		echo 25.11-pre
-		exit 0
-		;;
-	switch | up | down | update | reboot | build | ps | bash | dev | help)
-		SNOW_COMMAND="$opt"
-		;;
-	*)
-		case $SNOW_COMMAND in
-		switch | update | reboot | up | down | build | ps | bash | dev | help)
-			SNOW_COMMAND_ARGS+=("$opt")
+	# Process snow-specific options and commands before `--`
+	i=0
+	while [[ $i -lt ${#BEFORE_SEPARATOR[@]} ]]; do
+		opt="${BEFORE_SEPARATOR[$i]}"
+		i=$((i + 1))
+
+		case $opt in
+		-v | --verbose)
+			export VERBOSE=1
+			;;
+		-h | --help)
+			export HELP=1
+			;;
+		-b | --build)
+			export BUILD=1
+			;;
+		--version)
+			echo 25.11-pre
+			exit 0
+			;;
+		switch | up | down | update | reboot | build | ps | bash | dev | help)
+			SNOW_COMMAND="$opt"
 			;;
 		*)
-			if [[ -z $SNOW_COMMAND ]]; then
-				_iError "%s: unknown snow option '%s'. Use format: snow [options] -- command [args]" "$0" "$opt" >&2
-				exit 1
-			else
+			case $SNOW_COMMAND in
+			switch | update | reboot | up | down | build | ps | bash | dev | help)
 				SNOW_COMMAND_ARGS+=("$opt")
-			fi
+				;;
+			*)
+				if [[ -z $SNOW_COMMAND ]]; then
+					_iError "%s: unknown snow option '%s'. Use format: snow [options] -- command [args]" "$0" "$opt" >&2
+					exit 1
+				else
+					SNOW_COMMAND_ARGS+=("$opt")
+				fi
+				;;
+			esac
 			;;
 		esac
-		;;
-	esac
-done
+	done
 
-# Lets GOOOO!!!!!
-doBoot
+	# Lets GOOOO!!!!!
+	doBoot
 
-# Check if no `--` was found and no snow command was specified
-if [[ $found_separator == false && -z $SNOW_COMMAND ]]; then
-	doHelp >&2
-	exit 1
-fi
-
-# Handle snow-specific commands first
-if [[ -n $SNOW_COMMAND ]]; then
-	case $SNOW_COMMAND in
-
-	bash)
-		doSnowBash "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	build)
-		doSnowBuild "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	dev)
-		doSnowDev "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	down)
-		doSnowDown "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	ps)
-		doSnowPs "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	reboot)
-		doSnowReboot "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	switch)
-		doSnowSwitch "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	up)
-		doSnowUp "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	update)
-		doSnowUpdate "${SNOW_COMMAND_ARGS[@]}"
-		;;
-
-	help)
-		doHelp "${SNOW_COMMAND_ARGS[@]}"
-		;;
-	*)
-		_iError 'Unknown snow command: %s' "$SNOW_COMMAND" >&2
+	# Check if no `--` was found and no snow command was specified
+	if [[ $found_separator == false && -z $SNOW_COMMAND ]]; then
+		doHelp >&2
 		exit 1
-		;;
-	esac
-	exit 0
-fi
+	fi
 
-# None of the below should be run if SnowBlower is not up.
-isSnowBlowerUp
+	# Handle snow-specific commands first
+	if [[ -n $SNOW_COMMAND ]]; then
+		case $SNOW_COMMAND in
 
-doRoutedCommandExecute tools "${AFTER_SEPARATOR[@]}"
+		bash)
+			doSnowBash "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		build)
+			doSnowBuild "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		dev)
+			doSnowDev "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		down)
+			doSnowDown "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		ps)
+			doSnowPs "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		reboot)
+			doSnowReboot "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		switch)
+			doSnowSwitch "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		up)
+			doSnowUp "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		update)
+			doSnowUpdate "${SNOW_COMMAND_ARGS[@]}"
+			;;
+
+		help)
+			doHelp "${SNOW_COMMAND_ARGS[@]}"
+			;;
+		*)
+			_iError 'Unknown snow command: %s' "$SNOW_COMMAND" >&2
+			exit 1
+			;;
+		esac
+		exit 0
+	fi
+
+	# None of the below should be run if SnowBlower is not up.
+	isSnowBlowerUp
+
+	doRoutedCommandExecute tools "${AFTER_SEPARATOR[@]}"
+
+}
+
+doSnow "$@" || exit 1
